version: "3"

services:
  poll:
    build:
      context: ./poll
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
    networks:
      - poll-tier
    depends_on:
      - redis

  redis:
    image: redis:7
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dbname
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    depends_on:
      - redis
      - db
    networks:
      - back-tier
    restart: on-failure

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
    restart: on-failure

  result:
    restart: on-failure
    build:
      context: ./result
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dbname
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    depends_on:
      - "db"
    networks:
      - result-tier

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: